version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 
 
     # build image
     - run: |         
         docker info
         docker build -t aspnetapp -f Dockerfile .
     # deploy the image
     - run: |         
         docker login --username=$evgeniiaserg --password=$79e5eb5b-ff0c-4dee-9cbf-15d5517203e5 registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$funwithin/web
         docker push registry.heroku.com/$funwithin/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $funwithin